### ISSUE TITLE
How to validate the password?

### ISSUE THREAD

**Issue by bhuvaneshwariarkala** [jchambers/java-otp#1]
How to validate the generated OTP ?

**Comment by jchambers** [comment]
Do you mean "how do we validate that the password provided by a user is correct?" You should know the private key and the expected counter value (for HOTP) or time (for TOTP). Generate a password with those parameters (for TOTP, you might check a few times on either side of the expected time to account for clock drift) and see if the user's input matches any of the generated passwords.

**Comment by debjitk** [comment]
Can you elaborate a little

**Comment by debjitk** [comment]
My validation function is as follows:

`public static boolean validate(int otp, Duration duration, int length, String algorithm) throws NoSuchAlgorithmException, InvalidKeyException, NoSuchProviderException {

		final TimeBasedOneTimePasswordGenerator totp = new TimeBasedOneTimePasswordGenerator(duration, length, algorithm);
		final KeyGenerator generator = KeyGenerator.getInstance(totp.getAlgorithm());

		final Instant timestamp = OffsetDateTime.now(ZoneOffset.UTC).toInstant();
		
		final Instant timestampPrev = timestamp.minus(totp.getTimeStep());
		final Instant timestampNext = timestamp.plus(totp.getTimeStep());

		generator.init(512);

		final Key key = generator.generateKey();

		final int otpNow = totp.generateOneTimePassword(key, timestamp);

		final int otpPrev = totp.generateOneTimePassword(key, timestampPrev);
		final int otpNext = totp.generateOneTimePassword(key, timestampNext);

		if (otp == otpNow || otp == otpPrev || otp == otpNext)
			return true;

		return false;
	}`

The otp is never getting validated. What am i doing wrong ? The duration is 10 minutes
