### ISSUE TITLE
Release 0.1 not supported

### ISSUE THREAD

**Issue by mmoehring** [jchambers/java-otp#11]
Hello,

according to your README.md Release 0.1 is no longer supported but it is the only release available.
Do you plan release a new version anytime soon or should I vendor/submodule/subtree your repo?

Thanks

**Comment by mmoehring** [comment]
Closed because I will be using the reference implementation.

**Comment by jchambers** [comment]
> Release 0.1 is no longer supported but it is the only release available.

Both things are (temporarily) true. A more accurate way to describe the situation is that any fixes will happen in the next version, which may not be backward-compatible. There's nothing wrong with using 0.1.

> Do you plan release a new version anytime soon

Yes.
