### ISSUE TITLE
TOTP Generating different value with a particular timestep

### ISSUE THREAD

**Issue by debjitk** [jchambers/java-otp#13]
I have the following code setup for testing the library

```java
final Key key;
final KeyGenerator keyGenerator = KeyGenerator.getInstance(TimeBasedOneTimePasswordGenerator.TOTP_ALGORITHM_HMAC_SHA512);

keyGenerator.init(512);

key = keyGenerator.generateKey();

TimeBasedOneTimePasswordGenerator totp = new TimeBasedOneTimePasswordGenerator(Duration.ofSeconds(30), 6, TimeBasedOneTimePasswordGenerator.TOTP_ALGORITHM_HMAC_SHA512);

System.out.format("Time: %d Password:  %06d\n", Instant.now().getEpochSecond(), totp.generateOneTimePassword(key, Instant.now()));
			Thread.sleep(15 * 1000);
System.out.format("Time: %d Password:  %06d\n", Instant.now().getEpochSecond(), totp.generateOneTimePassword(key, Instant.now()));
			Thread.sleep(14 * 1000);
System.out.format("Time: %d Password:  %06d\n", Instant.now().getEpochSecond(), totp.generateOneTimePassword(key, Instant.now()));
```

Technically all the tree totp codes should be identical right ?

**Comment by jchambers** [comment]
> Technically all the tree totp codes should be identical right ?

No. If you're using a 30-second duration, two of those codes are guaranteed to fall into the same 30-second "bucket," and the third may or may not be in the same bucket.

If you run your example at 11:00:00, then the timestamps will be (roughly):

- 11:00:00
- 11:00:15
- 11:00:29

…and all three will be in the same bucket.

If you run your example at 11:00:20, then your three timestamps will be (again, roughly):

- 11:00:20
- 11:00:35
- 11:00:49

The first code will fall into the 30-second "bucket" from 11:00:00 (inclusive) to 11:00:30 (exclusive), but the latter two codes will fall into the 30-second "bucket" from 11:00:30 to 11:01:00.

**Comment by debjitk** [comment]
Yes of course. How stupid of me.

**Comment by jchambers** [comment]
It's an easy mistake to make; don't be so hard on yourself.
