### ISSUE TITLE
OTP generator return 5 digits instead of 6

### ISSUE THREAD

**Issue by majaode** [jchambers/java-otp#14]
Sometimes generateOneTimePassword returns 5 digits instead of 6. Not sure how to reproduce this

**Comment by jchambers** [comment]
`generateOneTimePassword` returns an `int`, and an `int` doesn't have any built-in notion of "number of digits." If you were to do this:

```
final int example = 12;
System.out.println(example);
```

…then you'd expect the output to be "12" and not "000012," right? The same thing is true with one-time passwords. When you generate a (six-digit) one-time password, you could wind up with a value anywhere between 0 and 999,999. If that value is 12, `System.out.println(oneTimePassword)` will just print "12."

What you need to do is:

```java
System.out.format("%06d\n", oneTimePassword);
```

…or:

```java
final String oneTimePasswordString = String.format("%06d", oneTimePassword);
```
