### ISSUE TITLE
Only one empty TimeBasedOneTimePasswordGenerator constructor available

### ISSUE THREAD

**Issue by vitsin** [jchambers/java-otp#24]
new TimeBasedOneTimePasswordGenerator() - works ok
new TimeBasedOneTimePasswordGenerator(Duration d) - the constructor is undefined
new TimeBasedOneTimePasswordGenerator(Duration d, int passLength) - the constructor is undefined
new TimeBasedOneTimePasswordGenerator(Duration d, int passLength, String hmacAlgo) - the constructor is undefined

running on v 0.3.0

**Comment by jchambers** [comment]
I'm sorry—I don't understand what you're reporting. Can you please elaborate? What do you mean by "the constructor is undefined?"

**Comment by vitsin** [comment]
sorry about that, I'll try other way.
In Java when I make a new instance by creating constructor of TimeBasedOneTimePasswordGenerator, only empty one is allowed.

ex:
TimeBasedOneTimePasswordGenerator totp = new TimeBasedOneTimePasswordGenerator(); // created ok!

when I try to do:
Duration d = Duration.newBuilder().setSeconds(45).build();
Integer passLength = 7;
String hmacAlgo = "SHA256";
new TimeBasedOneTimePasswordGenerator(d, passLength, hmacAlgo); // I am getting error "the constructor [bla] is undefined"

Hope it clarifies the issue I am experiencing.

**Comment by jchambers** [comment]
I think you're using the wrong kind of `Duration`. The constructor you're trying to use wants a [`java.time.Duration`](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html), which doesn't have a `newBuilder()` method. Are you perhaps using a `Duration` from some other package?

**Comment by vitsin** [comment]
what a mistake :-( thanks man
