### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;

### ISSUE THREAD

**Issue by trcoelho** [jchambers/java-otp#27]
Hello.
Recently I have this `java.lang.NoSuchMethodError ` on:

```
at com.eatthepath.otp.HmacOneTimePasswordGenerator.generateOneTimePassword(HmacOneTimePasswordGenerator.java:140)
	at com.eatthepath.otp.TimeBasedOneTimePasswordGenerator.generateOneTimePassword(TimeBasedOneTimePasswordGenerator.java:143)
```

I guess this is something related to the latest Java 1.8 updated version. Currently I am using:

```
openjdk version "**1.8.0_312**"
OpenJDK Runtime Environment (Temurin)(**build 1.8.0_312-b07**)
OpenJDK 64-Bit Server VM (Temurin)(build 25.312-b07, mixed mode)
```

Downloaded on https://adoptium.net/?variant=openjdk8 .

Curiously this wasn't happening on previous Java 1.8 update version.

I am trying to get more information about it and will update this issue as soon as I have, however could you please take a look on this? Perhaps we have more people facing same issue.

This is the version I am using, which I believe is the latest one:

```
<dependency>
	<groupId>com.eatthepath</groupId>
	<artifactId>java-otp</artifactId>
	<version>0.3.0</version>
</dependency>
```

Thanks in advance.

**Comment by trcoelho** [comment]
I also have tried with` IBM Semeru Runtime` as follows:
```
OpenJDK 8u312-b07
OpenJ9 0.29.0

```

And got the same:

```
java.lang.NoSuchMethodError: java/nio/ByteBuffer.clear()Ljava/nio/ByteBuffer; (loaded from C:\Program Files\Semeru\jdk-8.0.312.7-openj9\jre\lib\rt.jar by <Bootstrap Loader>) called from class com.eatthepath.otp.HmacOneTimePasswordGenerator (loaded from file:/C:/Users/tcoelho1/.m2/repository/com/eatthepath/java-otp/0.3.0/java-otp-0.3.0.jar by sun.misc.Launcher$AppClassLoader@6e1a46c1).
	at com.eatthepath.otp.HmacOneTimePasswordGenerator.generateOneTimePassword(HmacOneTimePasswordGenerator.java:140)
	at com.eatthepath.otp.TimeBasedOneTimePasswordGenerator.generateOneTimePassword(TimeBasedOneTimePasswordGenerator.java:143)
```

Hopefully it could be solved.

**Comment by jchambers** [comment]
This sounds like the same thing as https://github.com/jchambers/java-otp/discussions/26. I'll see what I can work out.

**Comment by trcoelho** [comment]
That exact the same thing. I believe if you compile this jar using JDK 1.8, it would work as expected.

**Comment by jchambers** [comment]
Agreed, but I think something else is wrong; JDK versions after 8 should still be able to target JDK 8, and I'm not sure why that's not happening. In any event, I'll be able to investigate in depth this weekend.

**Comment by trcoelho** [comment]
Alright, for now I have compiled sources using JDK 1.8 and worked fine. Let me know once you have an update about it and then I can use it as an artefact dependency.

Thank you @jchambers !

**Comment by jchambers** [comment]
There's something very fishy going on here. I pulled the .jar directly from Maven Central and inspected the contents:

```
$ javap -verbose HmacOneTimePasswordGenerator.class | fgrep major                                        
  major version: 52

$ javap -verbose TimeBasedOneTimePasswordGenerator.class| fgrep major
  major version: 52
```

…and major version 52 is definitely Java 8. So I don't _think_ that's the problem. I'll continue to dig.

**Comment by jchambers** [comment]
Ah—here's the problem: https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/

**Comment by jchambers** [comment]
I believe this should be fixed in #28 (so much for waiting for the weekend). Could you please check out that branch and let me know if things still build as expected for you under Java 8? All of the automated tests pass under Java 8, but given the circumstances, first-hand confirmation would be great, too.

Thanks kindly!

**Comment by trcoelho** [comment]
Hi @jchambers , have checked out branch release_8, run `mvn clean install`, and then imported the generated jar under `target/java-otp-0.3.1-SNAPSHOT` and it did work. 

Here's the Java version that I used to achieve this result and also use on projects:

```
$ java -version
openjdk version "1.8.0_312"
IBM Semeru Runtime Open Edition (build 1.8.0_312-b07)
Eclipse OpenJ9 VM (build openj9-0.29.0, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20211022_236 (JIT enabled, AOT enabled)
OpenJ9   - e1e72c497
OMR      - 299b6a2d2
JCL      - 8860d39588 based on jdk8u312-b07)
```
Also the Maven version:

```
$ mvn -version
Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: C:\apache-maven-3.8.3
Java version: 1.8.0_312, vendor: International Business Machines Corporation, runtime: C:\Program Files\Semeru\jdk-8.0.312.7-openj9\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

Could you please let me know once you upload this new version to maven repository so I can use it directly on my `pom.xml`?

Thanks in advance.

**Comment by jchambers** [comment]
A new release is on its way to Maven Central right now.

**Comment by trcoelho** [comment]
Have imported the new artefact 0.3.1 from maven central and successfully worked! Thank you @jchambers !
