### ISSUE TITLE
Tests use "RAW" as algorithm for keys

### ISSUE THREAD

**Issue by flozano** [jchambers/java-otp#31]
Here:
https://github.com/jchambers/java-otp/blob/46670ad0cf991e2ccbe339ddd5e5cb9dabf00a17/src/test/java/com/eatthepath/otp/TimeBasedOneTimePasswordGeneratorTest.java#L47

the 2nd argument should be the algorithm, but RAW is passed instead.

**Comment by jchambers** [comment]
Good catch! Thank you!

Also: good to hear from you—happy new year to you!

**Comment by flozano** [comment]
😀 I was looking for an aerogear otp replacement and was so pleasantly surprised to see who made this one 😀

Happy new year and thanks a lot for the great stuff you code and share!
