### ISSUE TITLE
Using a secret

### ISSUE THREAD

**Issue by arifainchtein** [jchambers/java-otp#5]
Hello,
Given that TOTP needs a shared secret string, how will you generate the code using your library starting from a string?  I am planning to embed your library in an app where the user will have  another TOTP compliant app to generate the user code that will be compared against the TOTP created by your library.  In your example usage you start with a random key.
Any chance you could create an example that starts with a string as a shared secret?

thanks

**Comment by jchambers** [comment]
> Any chance you could create an example that starts with a string as a shared secret?

Flatly, no. Sorry. Key management is a Serious Security Topic™, and I don't want to do anything that could be construed as giving out security advice. If you're just asking "how do I turn persisted data into a key using Java," you might start your research with the [`SecretKeyFactory`](https://docs.oracle.com/javase/8/docs/api/javax/crypto/SecretKeyFactory.html) interface.
